[[agents]]
name = "Engineering Assistant"
description = "A general-purpose coding assistant."
llm_model_name = "google-gla:gemini-2.5-pro-preview-05-06" # Example, choose a model you have access to
system_prompt = "You are a software engineering assistant. Warn if you notice you have access to people names or sensitive information"
data_classification = "public"
mcp_servers = [
    "markdown_server",
    "macos_system_server",
    "custom_git_server",
    "main_git_server",
    "cortex_server",
    "newrelic_server",
    "openapi_server",
    "filesystem_server",
    "fetch_server",
    "search_server",
    "sqlite_server",
    "processing_history_server",
    "datetime_server",
    "rag_crawler_server"
]

[[agents]]
name = "Private Data Analyst"
description = "A data analysis assistant that can access private data sources and perform analysis."
llm_model_name = "GLM-4-32B-0414-4bit-DWQ", 
base_url = "http://localhost:8080/api/v1" 
system_prompt = "You are a data analysis assistant with access to private data sources and tools. You can perform analysis and answer questions based on the data."
data_classification = "internal-only"
mcp_servers = [
    "macos_system_server",
    "main_git_server",
    "filesystem_server",
    "fetch_server",
    "search_server",
    "sqlite_server",
    "processing_history_server",
    "datetime_server",
    "rag_crawler_server"
]

