[project]
name = "agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "logfire>=3.12.0",
    "mcp-server-fetch>=2025.1.17",
    "pydantic-ai>=0.0.52",
    "pylint>=3.3.6",
    "tool>=0.8.0",
]

