[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "llm-and-me-agents"
version = "0.1.0"
description = "Agents for LLM and Me"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "llm-and-me-tools",
    "dotenv>=0.9.9",
    "logfire>=3.12.0",
    "pydantic-ai>=0.0.52",
    "pylint>=3.3.6",
    "tool>=0.8.0",
]

[tool.uv.sources]
llm-and-me-tools = { workspace = true }

[project.scripts]
llm_and_me_agents = "llm_and_me_agents:main"

