[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "llm-and-me-tools" 
version = "0.1.0"
description = "Tools for LLM and Me"
requires-python = ">=3.11" 
dependencies = [
    "fastmcp>=2.1.2",
    "requests>=2.30.0", # Added for making HTTP requests
    "python-dotenv>=1.0.0", # Added for loading .env files
    "pydantic>=2.0.0", # Added for data validation and modeling
]

[project.scripts]
git-tools-mcp-server = "llm_and_me_tools:git_tools_main"
macos-mcp-server = "llm_and_me_tools:macos_main"
markdown-mcp-server = "llm_and_me_tools:markdown_main"
cortex-mcp-server = "llm_and_me_tools:cortex_main" # Added Cortex server
openapi-mcp-server = "llm_and_me_tools.openapi_mcp_server:main" # Added OpenAPI server
json-to-sqlite = "llm_and_me_tools.json_to_sqlite:main"
newrelic-mcp-server = "llm_and_me_tools.newrelic_mcp_server:main" # Added New Relic server

[tool.setuptools.packages.find]
where = ["src"]

