[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "llm-and-me-tools" 
version = "0.1.0"
description = "Tools for LLM and Me"
requires-python = ">=3.11" 
dependencies = [
    "fastmcp>=2.1.2",
]

[project.scripts]
git-tools-mcp-server = "llm_and_me_tools:git_tools_main"
macos-mcp-server = "llm_and_me_tools:macos_main"
markdown-mcp-server = "llm_and_me_tools:markdown_main"

[tool.setuptools.packages.find]
where = ["src"]

